Repository plentymarkets/plugin-io, pull requests merged in 2020-03, with the labels that each got.

#755 LocalizedOrder.php - add variation properties
  src/Models/LocalizedOrder.php
Labels: early required

#760 UDPATE move place order logic to core
  src/Controllers/PlaceOrderController.php
  src/Providers/IOServiceProvider.php
  src/Services/OrderService.php
Labels: blocked

#758 ADD search suggestions
  src/Services/ItemListService.php
  src/Services/ItemSearchAutocompleteService.php
Labels: testing in progress

#769 UPDATE language change and auth events for handling item sets
  src/Providers/IOServiceProvider.php
  src/Services/BasketService.php
Labels: testing in progress

#763 Revert "Revert "UDPATE move place order logic to core""
  src/Controllers/PlaceOrderController.php
  src/Providers/IOServiceProvider.php
  src/Services/OrderService.php
Labels: beta required, blocked

#772 ADD item search did you mean suggestions
  src/Services/ItemSearchAutocompleteService.php
Labels: testing in progress

#785 Item sets/attribute markup for overlay
  src/Api/ApiResponse.php
Labels: testing in progress
